#!/bin/bash -il

SCRIPT_PATH=$(dirname $0)

cd ${SCRIPT_PATH}

STORAGE_DIR=${HOME}/.aion
LOG_DIR=${STORAGE_DIR}/log
JAVA_INSTALL=${STORAGE_DIR}/jre-10.0.2.jre/Contents/Home
JAVA_CMD=${JAVA_INSTALL}/bin/java

if [ ! -f ${JAVA_CMD} ] || [ $(${JAVA_CMD} -version 2>&1 | grep "10.0.2" | wc -l) -lt 1 ]
 then
  mkdir -p ${JAVA_INSTALL}
   tar -xzf jre-10.0.2.tar.gz -C ${STORAGE_DIR}
fi

LEDGER=${SCRIPT_PATH}/native/mac/ledger
HID=${LEDGER}/hid
PATH=$PATH:${HID}/node-v8.11.4-darwin-x64/bin
if [ ! -d ${HID} ]
 then
  pushd ${LEDGER}
  pwd
  tar -xzf hid.tar.gz
  pushd ${HID}
  pwd
  npm i -g npm
  npm install
  pwd
  popd
  popd
  open -a AionWallet
 else
  LIB_DIR=$(cd ../Java && pwd)/*
  mkdir -p ${LOG_DIR}
  ${JAVA_CMD} -cp "${LIB_DIR}" -Dlocal.storage.dir=${STORAGE_DIR} -Xms300m -Xmx500m org.aion.wallet.WalletApplication &> ${LOG_DIR}/log
fi

